# Generated by Django 4.2.3 on 2023-07-29 20:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdrawal'), ('transfer', 'Transfer')], default='transfer', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('User', models.ForeignKey(on_delete=models.SET('Deleted User'), related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
