# Generated by Django 4.2.3 on 2023-07-29 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='User',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transfer', serialize=False, to='bank.transaction')),
                ('receiver', models.ForeignKey(null=True, on_delete=models.SET('Deleted User'), related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
