# Generated by Django 4.2.3 on 2023-08-02 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0002_rename_user_transaction_user_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted User'), related_name='received_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
