# Generated by Django 4.2.3 on 2023-08-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='alert',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='credit', max_length=8),
        ),
    ]
