# Generated by Django 4.2.3 on 2023-08-05 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0006_transaction_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='alert',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted User'), related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
