# Generated by Django 4.2.3 on 2023-07-06 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'PIN must be a 4-digit number.')]),
        ),
    ]
