# Generated by Django 4.2.3 on 2023-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newlyCreated',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
