# Generated by Django 4.2.3 on 2023-07-29 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_newlycreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'PIN must be a 4-digit number.')]),
        ),
    ]
